### ISSUE TITLE
ARM64 Telegram invite link is broken

### ISSUE THREAD

**Issue by quiret** [WOA-Project/Lumia-Drivers#10]
![image](https://user-images.githubusercontent.com/7682485/90615998-24ea2b80-e20d-11ea-8432-ae831e422085.png)

URL: https://t.me/joinchat/C-AWlUUp3wxnBQeuxIEVow

When trying to join the Telegram group it says that the invite link is expired (?).

**Comment by gus33000** [comment]
Fixed
