### ISSUE TITLE
Status page?

### ISSUE THREAD

**Issue by TSlivede** [WOA-Project/Lumia-Drivers#11]
The readme on this repository

https://github.com/WOA-Project/Lumia-Drivers/blob/master/README.md#user-content-project-status

still points to the wiki on the old repository

https://github.com/WOA-Project/MSM8994-8992-NT-ARM64-Drivers/wiki/Status

---

Is there a up to date status page somewhere? Or is the wiki on the old repo still updated?

**Comment by gus33000** [comment]
Thank you for the heads up. Yes there is a new status page, unfortunately it appears we forgot to link it on this repository, you can find it here in the meantime: https://woa-project.github.io/LumiaWOA/status/
