### ISSUE TITLE
Switch the device into mass storage.

### ISSUE THREAD

**Issue by jabadabado** [WOA-Project/Lumia-Drivers#31]
Great project!

I would love to see Windows 11 on my never used Microsoft Lumia 950 XL. But how do I switch it into Mass Storage mode? I have searched internet and tried some instructions, loading Zune etc, but with no success. I can not get a drive letter assigned to the phone, any suggestions?

Jabba

**Comment by gus33000** [comment]
follow the guides available here: https://woa-project.github.io/LumiaWOA/guides/
